#ifndef DEFINES_h
#define DEFINES_h

#define SAMPLES_PER_BLOCK 512
#define DMA_BUF_SIZE SAMPLES_PER_BLOCK*2

#define MESSAGE_SIZE SAMPLES_PER_BLOCK*2
#define UART_BUF_SIZE MESSAGE_SIZE*4

#endif // DEFINES_h